import os
import tempfile
import traceback
from fastapi import APIRouter, UploadFile, File, HTTPException, BackgroundTasks
from fastapi.responses import JSONResponse
from app.schemas.schemas import PolicyAnalysisResponse
from app.services.pipeline import get_pipeline_controller
from app.utils.logger import logger
from app.core.config import settings

router = APIRouter()

@router.post("/analyze", response_model=PolicyAnalysisResponse)
async def analyze_policy(file: UploadFile = File(...)):
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file provided")
        
    ext = os.path.splitext(file.filename)[1].lower()
    if ext not in [".pdf", ".txt", ".html", ".htm", ".xml"]:
        raise HTTPException(status_code=400, detail="Invalid file type. Accepted: PDF, TXT, HTML, XML")
        
    logger.info(f"Received file for analysis: {file.filename}")
    
    # Save uploaded file to temporary location
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as tmp:
            content = await file.read()
            if not content:
                raise HTTPException(status_code=400, detail="Empty policy file")
            tmp.write(content)
            tmp_path = tmp.name
    except Exception as e:
        logger.error(f"Failed to save uploaded file: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to process upload")
        
    try:
        controller = get_pipeline_controller()
        report = controller.process_policy(tmp_path)
        if "summary" in report:
            report["summary"]["title"] = file.filename
            
        history_dir = os.path.join(settings.TRUSTTEXT_ROOT, "Backend", "History")
        os.makedirs(history_dir, exist_ok=True)
        import json
        with open(os.path.join(history_dir, f"{report.get('analysis_id', file.filename)}.json"), 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=4)
            
        return JSONResponse(content=report)
    except Exception as e:
        logger.error(f"Analysis failed: {str(e)}")
        logger.error(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

@router.get("/history")
def get_history():
    history_dir = os.path.join(settings.TRUSTTEXT_ROOT, "Backend", "History")
    history_list = []
    if os.path.exists(history_dir):
        import json
        for file in os.listdir(history_dir):
            if file.endswith(".json"):
                try:
                    with open(os.path.join(history_dir, file), 'r', encoding='utf-8') as f:
                        data = json.load(f)
                        # Ensure we don't send the entire finding list just for history summary
                        summary = data.get("summary", {})
                        history_list.append({
                            "analysis_id": data.get("analysis_id", file.replace(".json", "")),
                            "title": summary.get("title", "Unknown Policy"),
                            "app_context": summary.get("app_context", "Unknown"),
                            "execution_metadata": summary.get("execution_metadata", {}),
                            "findings_count": len(data.get("findings", []))
                        })
                except Exception as e:
                    logger.error(f"Error reading history file {file}: {e}")
                    
    # Sort by recent first (if we had timestamp we would sort by it, here just assume directory read order)
    return {"history": history_list}

@router.get("/history/{analysis_id}")
def get_history_detail(analysis_id: str):
    history_file = os.path.join(settings.TRUSTTEXT_ROOT, "Backend", "History", f"{analysis_id}.json")
    if os.path.exists(history_file):
        import json
        with open(history_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # The saved data is already the complete report generated by the pipeline
        return data
    
    raise HTTPException(status_code=404, detail="Analysis not found")
            
@router.delete("/history/{analysis_id}")
def delete_history_detail(analysis_id: str):
    history_file = os.path.join(settings.TRUSTTEXT_ROOT, "Backend", "History", f"{analysis_id}.json")
    if os.path.exists(history_file):
        try:
            os.remove(history_file)
            return {"status": "success", "message": f"Deleted {analysis_id}"}
        except Exception as e:
            logger.error(f"Failed to delete history file {analysis_id}: {str(e)}")
            raise HTTPException(status_code=500, detail="Failed to delete history file")
    
    raise HTTPException(status_code=404, detail="Analysis not found")

@router.get("/health")
def health_check():
    # Attempt to initialize controller to verify models load
    try:
        get_pipeline_controller()
        return {"status": "healthy"}
    except Exception as e:
        logger.error(f"Health check failed: {str(e)}")
        raise HTTPException(status_code=503, detail="Service unavailable")

@router.get("/version")
def version_info():
    return {
        "project": settings.PROJECT_NAME,
        "version": settings.VERSION
    }
